# Generated by Django 5.1.2 on 2024-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="View Count"),
        ),
    ]
