# Generated by Django 5.1.2 on 2024-10-22 06:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, verbose_name="Unique Verification UUID"
            ),
        ),
    ]
